#!/usr/bin/env python2

from bottle import *

@route('/')
def route_to_index():
	return static_file('index.html', root='.')

@route('/<filename:path>')
def send_static(filename):
    return static_file(filename, root='.')

run(host='localhost', port=8080)
